#!/bin/sh

#######
#Readme
#------
#There are two parts in this scripts, please comment one of them before continue
#######


#######
#Part-1
#######
#On SOURCE machine, zip the NEW codes
tar zcvf NEWCodes_20110531.tar.gz $FOAM_SRC/OpenFOAM/interpolations/RBFInterpolation $FOAM_SRC/postProcessing/functionObjects/RBFMotion $FOAM_SRC/postProcessing/functionObjects/Allwmake $FOAM_SRC/dynamicMesh/meshMotion/RBFMotionSolver


#######
#Part-2
#######
#On TARGET machine, backup the OLD codes, and them remove them and then unzip the NEW codes that is zipped from the SOURCE machine.
#tar zcvf OLDCodes_20110531.tar.gz $FOAM_SRC/OpenFOAM/interpolations/RBFInterpolation $FOAM_SRC/postProcessing/functionObjects/RBFMotion $FOAM_SRC/postProcessing/functionObjects/Allwmake $FOAM_SRC/dynamicMesh/meshMotion/RBFMotionSolver
#rm -rf $FOAM_SRC/OpenFOAM/interpolations/RBFInterpolation $FOAM_SRC/postProcessing/functionObjects/RBFMotion $FOAM_SRC/postProcessing/functionObjects/Allwmake $FOAM_SRC/dynamicMesh/meshMotion/RBFMotionSolver
#tar zxvf NEWCodes_20110531.tar.gz $FOAM_SRC/OpenFOAM/interpolations/RBFInterpolation $FOAM_SRC/postProcessing/functionObjects/RBFMotion $FOAM_SRC/postProcessing/functionObjects/Allwmake $FOAM_SRC/dynamicMesh/meshMotion/RBFMotionSolver
